split api calls
LiorGnieslawMoveo/pokemonApp pull request #4
Opened 2024-03-25 12:52 UTC by LiorGnieslawMoveo

2024-03-25 14:35 UTC, Karina-Moveo requested changes

2024-03-25 14:35 UTC, Karina-Moveo commented on src/app/components/history/history.component.ts
> +
Remoce extra space

2024-03-25 14:35 UTC, Karina-Moveo commented on src/app/services/pokemon.service.ts
> +  private isLoggedInSubject: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(this.cookieService.get('isLoggedIn') === 'true');
No need to check equal to true

2024-03-25 14:35 UTC, Karina-Moveo commented on src/app/services/pokemon.service.ts
> +        imageUrl: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${this.extractPokemonIdFromUrl(pokemon.url)}.png`,
move it out into a const

2024-03-25 14:35 UTC, Karina-Moveo commented on src/app/services/pokemon.service.ts
> +      imageUrl: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${this.extractPokemonIdFromUrl(url)}.png`,
move into const

2024-03-26 13:59 UTC, LiorGnieslawMoveo commented on src/app/services/pokemon.service.ts
> +  private isLoggedInSubject: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(this.cookieService.get('isLoggedIn') === 'true');
this.cookieService.get('isLoggedIn') returns a string so I need do this check to enter the subject a boolean value.

2024-03-26 17:11 UTC, Karina-Moveo approved these changes

2024-03-26 22:25 UTC, merged